import 'package:flutter/material.dart';
import "package:gvp_sim_db/database/moor_database.dart";
import 'package:gvp_sim_db/buttonData.dart';
import 'package:gvp_sim_db/event.dart';
import 'package:gvp_sim_db/eventState.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

class DataStorage {

  static const SKILLCOUNT = 9;
  static const INNITSTATECOUNT = 2;
  static const EVENTSTATECOUNT = 16;

  static List<Skill> skills = [
    Skill(
      name: "Kytara",
      currentHours: 0,
      currentLevel: 1,
      levelUp: [2,4,10,18],
      available: true,
    ),
    Skill(
      name: "Diplomacie",
      currentHours: 0,
      currentLevel: 1,
      levelUp: [1,4,5],
      available: true,
    ),
    Skill(
      name: "Balls",
      currentHours: 0,
      currentLevel: 0,
      levelUp: [2,1,6,10,14,15,20],
      available: true,
    ),
    Skill(
      name: 'Flutter',
      currentHours: 0,
      currentLevel: 3,
      levelUp: [5,8,10,15,25,80],
      available: true,
    ),
    Skill(
      name: "Fotbal",
      currentHours: 0,
      currentLevel: 3,
      levelUp: [3,5,8,10,15],
      available: true,
    ),
    Skill(
      name: "Šplhoun",
      currentHours: 0,
      currentLevel: 0,
      levelUp: [6,8,10,12,15],
      available: false,
    ),
    Skill(
      name: 'Pythágorovka',
      currentHours: 0,
      currentLevel: 0,
      levelUp: [10,15,18,20],
      available: false,
    ),
    Skill(
      name: "Parkur",
      currentHours: 0,
      currentLevel: 0,
      levelUp: [6,8,10],
      available: false,
    ),
    Skill(
      name: "Kamenná játra",
      currentHours: 0,
      currentLevel: 0,
      levelUp: [3,8,10],
      available: false,
    ),

  ];

  static  Map<String, IconData> skillIcons= {
    'Kytara' : MdiIcons.guitarAcoustic,
    'Flutter' : MdiIcons.xml,
    'Diplomacie' : MdiIcons.newspaper,
    'Balls' : MdiIcons.pokeball,
    "Šplhoun" : MdiIcons.glasses,
    "Fotbal" : MdiIcons.soccer,
    'Pythágorovka' : MdiIcons.triangleOutline,
    "Parkur" : MdiIcons.jumpRope,
    "Kamenná játra": MdiIcons.beer,
  };

//todo: tvuj program dela initStateID s malym 'd'

  static List<int> innitStateIDs = [
    10010, 10110
  ];

  static List<EventState> eventStates = [
    EventState(id: 10010, sentence: "Je začátek školního roku a hodně učitelů odjelo na seznamovací kurzy. Stalo se tak, že před laborkama z chemie je v rozvrhu čtyřhodinová díra. Tvoji spolužáci tě vyslali poprosit Vondy, aby hodina odpadla. Stojíš před kabinetem a klepeš na dveře.\n\"Dále!\"",
        personName: "Vondy", imagePath: "images/vondy.jpg",
        butt1: ButtonData(text: "...", nextID: 10011,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt2: ButtonData(text: "...", nextID: 10011,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt3: ButtonData(text: "...", nextID: 10011,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "...", nextID: 10011,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10013, sentence: "\"No to to teda moc neumíš. Buď rád(a), že nedostaneš pětku s váhou 10. Opakování očividně potřebujete jako sůl. Hodina bude!\"",
        personName: "Vondy", imagePath: "images/vondy.jpg",
        butt1: ButtonData(text: "Ach jo...", nextID: 10010,
            isFinal: true, finalSentence: "Tak to se ti teda nepovedlo... Alespoň můžete jít na fotbal.",
            unlocksSkill: "none",
            effects: {"happiness": -10, "peerPopularity": -5, "teacherPopularity": -5}),
        butt2: ButtonData(text: "No dobře...", nextID: 10010,
            isFinal: true, finalSentence: "Tak to se ti teda nepovedlo... Alespoň můžete jít na fotbal.",
            unlocksSkill: "none",
            effects: {"happiness": -10, "peerPopularity": -5, "teacherPopularity": -5}),
        butt3: ButtonData(text: "Zkoušet to dál.", nextID: 10015,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "To není fér :(", nextID: 10010,
            isFinal: true, finalSentence: "Život není fér.",
            unlocksSkill: "none",
            effects: {"happiness": -15, "peerPopularity": -15, "teacherPopularity": -1 })),
    EventState(id: 10015, sentence: "A nemohl bych vás nějak přesvědčit?",
        personName: "Vondy", imagePath: "images/vondy.jpg",
        butt1: ButtonData(text: "Vydírat", nextID: 10010,
            isFinal: true, finalSentence: "aaa",
            unlocksSkill: "none"),
        butt2: ButtonData(text: "Vytáhnout peněženku", nextID: 10010,
            isFinal: true, finalSentence: "No pokud mě pozveš na párek v rohlíku u paní Dany, tak by se to možná dalo zařídit...",
            unlocksSkill: "none",
            effects: {"money": -15, "happiness": 10, "peerPopularity": 5, "teacherPopularity": 5 }),
        butt3: ButtonData(text: "Uplatnit šarm", nextID: 10010,
            isFinal: true, finalSentence: "aaa",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "Prosit na kolenou", nextID: 10010,
            isFinal: true, finalSentence: "aaa",
            unlocksSkill: "none")),
    EventState(id: 10011, sentence: "\"Dobrý den, paní profesorko. Nemohly by nám dnes odpadnout laborky? Máme přeci stejně jen něco opakovat a my bychom tu museli čtyři hodiny čekat...\"\n\"No dobře, jestli máme jen opakovat, tak si tě teda vyzkouším. Co je C6H12O6?\", ptá se Vondy trochu podrážděně, ale usmívá se.",
        personName: "Vondy", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Fruktóza", nextID: 10013,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt2: ButtonData(text: "Sírovka?", nextID: 10013,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt3: ButtonData(text: "Glukóza", nextID: 10012,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "Diamant", nextID: 10013,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10012, sentence: "\"No dobře, a jaká je elektronová konfigurace vanadu?\"",
        personName: "Vondy", imagePath: "images/vondy.jpg",
        butt1: ButtonData(text: "[Ar] 3d3 4s2", nextID: 10010,
            isFinal: true, finalSentence: "Panečku, fakt to umíš! No možná bychom to jednou mohli vynechat...",
            unlocksSkill: "none",
            effects: {"happiness": 10, "peerPopularity": 5, "teacherPopularity": 10 }),
        butt2: ButtonData(text: "[vanad]", nextID: 10013,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt3: ButtonData(text: "[Ar] 4d2 3s3", nextID: 10013,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "[Ar] 3d2 4s3", nextID: 10013,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10110, sentence: "Tábor stojí a oheň plápolá. Hvězdy svítí a je teplo. ideální večer na... Na co vlastně?",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Jít spát", nextID: 10110,
            isFinal: true, finalSentence: "Ráno jsi se probudil sice odpočatý, ale s pomalovaným obličejem a spacákem plným mouky. Všichni se ti bez ostychu smějí.",
            unlocksSkill: "none",
            effects: {"sleep": 10, "happiness": -10}),
        butt2: ButtonData(text: "Hraní na kytaru", nextID: 10111,
            isFinal: false, finalSentence: "",
            requirements: ["Kytara", 2],
            unlocksSkill: "none"),
        butt3: ButtonData(text: "Chlastání s kamarády", nextID: 10112,
            isFinal: false, finalSentence: "",
            unlocksSkill: "Kamenná játra"),
        butt4: ButtonData(text: "Hrát karty", nextID: 10110,
            isFinal: true, finalSentence: "větev není napsaná",
            unlocksSkill: "none")),
    EventState(id: 10112, sentence: "Postupně všichni odchází spát, až už ti dělá společnost jenom Vašek.\n\"Tak co dáme?\"",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Jäger", nextID: 10113,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -4}),
        butt2: ButtonData(text: "Vodka", nextID: 10113,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -4}),
        butt3: ButtonData(text: "Absint", nextID: 10113,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -5}),
        butt4: ButtonData(text: "Vaječňák", nextID: 10113,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -3})),
    EventState(id: 10113, sentence: "To by chtělo něčím zapít... Jaký dáme pivo?",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Plzeň", nextID: 10114,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -3, "money": -5}),
        butt2: ButtonData(text: "Gambrinus", nextID: 10114,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -5}),
        butt3: ButtonData(text: "Braníček", nextID: 10114,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -4, "happiness": 5}),
        butt4: ButtonData(text: "Kozel", nextID: 10114,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -3})),
    EventState(id: 10114, sentence: "A na dobrou noc?",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Už raději ne", nextID: 10110,
            isFinal: true, finalSentence: "Ještě celkem střízlivý zalézáš do spacáku. I tak ses ale trochu chlastat naučil.",
            unlocksSkill: "none"),
        butt2: ButtonData(text: "Griotka", nextID: 10110,
            isFinal: true, finalSentence: "Konečně jsi se naučil pořádně chlastat! A ještě k tomu se více skamarádil s Vaškem. Potácíš se ke stanu.",
            unlocksSkill: "none",
            effects: {"happiness": 10}),
        butt3: ButtonData(text: "Fernet", nextID: 10110,
            isFinal: true, finalSentence: "Konečně jsi se naučil pořádně chlastat! A ještě k tomu se více skamarádil s Vaškem. Potácíš se ke stanu.",
            unlocksSkill: "none",
            effects: {"happiness": 10}),
        butt4: ButtonData(text: "Džin", nextID: 10110,
            isFinal: true, finalSentence: "Konečně jsi se naučil pořádně chlastat! A ještě k tomu se více skamarádil s Vaškem. Potácíš se ke stanu.",
            unlocksSkill: "none",
            effects: {"happiness": 10})),
    EventState(id: 10111, sentence: "Vytáhl jsi kytaru. Holky čekají, že zahraješ nějakou slaďárnu. Kámoši se těší na nějaký meme a učitelé doufají, že to nebude sprosté. Co zahraješ?",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Buráky", nextID: 10110,
            isFinal: true, finalSentence: "tato větev není napsaná",
            unlocksSkill: "none", requirements: ["Kytara", 1]),
        butt2: ButtonData(text: "Oasis - Wonderwall", nextID: 10115,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none", requirements: ["Kytara", 2],
            effects: {"sleep": -5, "happiness": -10, "peerPopularity": 5, "teacherPopularity": 5}),
        butt3: ButtonData(text: "Stairway to heaven", nextID: 10110,
            isFinal: true, finalSentence: "tato větev není napsaná",
            unlocksSkill: "none", requirements: ["Kytara", 3]),
        butt4: ButtonData(text: "Depešmód", nextID: 10110,
            isFinal: true, finalSentence: "Kytaru si úspěšně rozflákal při prvním songu.",
            unlocksSkill: "none", requirements: ["Kytara", 4],
            effects: {"money": -20, "happiness": 20, "peerPopularity": -10, "parentPopularity": -10, "teacherPopularity": -10})),
    EventState(id: 10115, sentence: "Na klín si ti sedne Ema. \n\"To jsi zahrál nádherně,\" zašeptá ti do ucha.\nJe to nejhezčí holka ze třídy a do teď se na tebe za ty roky podívala sotva dvakrát. Zvláštní...",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Chceš to taky naučit?", nextID: 10116,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt2: ButtonData(text: "Eh.. No.. Dík..", nextID: 10116,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt3: ButtonData(text: "...", nextID: 10115,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "...", nextID: 10115,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10116, sentence: "Ty jsi roztomilej.  Co kdybys na mě počkal dole u kánojí? Něco ti ukážu.",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: ";)", nextID: 10117,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt2: ButtonData(text: "Jasně", nextID: 10117,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt3: ButtonData(text: "No tak jo...", nextID: 10117,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "Radši půjdu spát", nextID: 10110,
            isFinal: true, finalSentence: "Vyspal jsi dobře a sám.",
            unlocksSkill: "none",
            effects: {"sleep": 10, "happiness": -5})),
    EventState(id: 10117, sentence: "Nenápadně jsi se vytratil od ostatních a posadil se u kánoje Tsunami. ",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Čekat", nextID: 10118,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -10, "happiness": -5}),
        butt2: ButtonData(text: "Jít spát", nextID: 10110,
            isFinal: true, finalSentence: "Vyspal jsi se dobře, ale sám.",
            unlocksSkill: "none",
            effects: {"happiness": -5}),
        butt3: ButtonData(text: "...", nextID: 10117,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "...", nextID: 10117,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10118, sentence: "Sedíš tu už skoro půl hodiny a Eva nikde. Citíš se jako pornohvězda na premiéře. ",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Čekat", nextID: 10119,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -10, "happiness": -5}),
        butt2: ButtonData(text: "Jít spát", nextID: 10110,
            isFinal: true, finalSentence: "Moc si se nevyspal. A ještě k tomu jsi byl sám.",
            unlocksSkill: "none",
            effects: {"sleep": -5, "happiness": -10}),
        butt3: ButtonData(text: "...", nextID: 10118,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "...", nextID: 10118,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10119, sentence: "Další půl hodina minula a tobě se klíží oči. Stojí to vůbec za to?",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "ANO!", nextID: 10120,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none",
            effects: {"sleep": -10, "happiness": -5}),
        butt2: ButtonData(text: "Ne, jdu spát", nextID: 10110,
            isFinal: true, finalSentence: "Když usínáš tak už pomalu svítá. Stýská se ti po Evě.",
            unlocksSkill: "none",
            effects: {"sleep": -5, "happiness": -10}),
        butt3: ButtonData(text: "...", nextID: 10119,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "...", nextID: 10119,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
    EventState(id: 10120, sentence: "Je ti jasné, že už dlouho nevydržíš. Ale věříš, že tě Eva příjemně probudí. Usínáš na kánoji Tsunami?",
        personName: "Ohýnek", imagePath: "images/ohynek.jpg",
        butt1: ButtonData(text: "Ano Evo!", nextID: 10110,
            isFinal: true, finalSentence: "Pomalu přecházíš do světa snů. Myslíš při tom na Eviny přednosti.",
            unlocksSkill: "none",
            effects: {"sleep": -30}),
        butt2: ButtonData(text: "Raději jdu spát", nextID: 10110,
            isFinal: true, finalSentence: "V polospánku jsi se nějak dostal do spacáku. Ta Eva je ale mrcha!",
            unlocksSkill: "none",
            effects: {"sleep": -5, "happiness": -5}),
        butt3: ButtonData(text: "...", nextID: 10120,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none"),
        butt4: ButtonData(text: "...", nextID: 10120,
            isFinal: false, finalSentence: "",
            unlocksSkill: "none")),
  ];
}